NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
bltm <- subset(NEI, fips == "24510")
bltm_ems <- tapply(bltm$Emissions, bltm$year, sum)
bltm_ems_type <- aggregate(Emissions ~ year + type, bltm, sum)
library(ggplot2)
png("plot3.png")
ggplot(bltm_ems_type, aes(x = year, y = Emissions, color = type)) + geom_line() + xlab("Year") + ylab("Total PM2.5 Emissions (tons)") + ggtitle("Total PM2.5 Emissions in Baltimore by Year and Type")
dev.off()