fulldata <- read.csv("household_power_consumption.txt", header = T, sep = ';', na.strings = "?", nrows = 2075259, check.names = F, stringsAsFactors = F, comment.char = "", quote = '\"')
fulldata$Date <- as.Date(fulldata$Date, format = "%d/%m/%Y")
finaldata <- subset(fulldata, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
rm(fulldata)
date_time <- paste(as.Date(finaldata$Date), finaldata$Time)
finaldata$Datetime <- as.POSIXct(date_time)
plot(finaldata$Global_active_power ~ finaldata$Datetime, type = "l", ylab = "Global Active Power (kilowatts)", xlab="")
dev.copy(png, file = "plot2.png", height = 480, width = 480)
dev.off()
